# Generated by Django 5.0.6 on 2024-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('calumnos', models.PositiveSmallIntegerField()),
                ('destino', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
            ],
        ),
    ]
